debug: false

replicaCount: 1

image:
  repository: reanahub/reana-server
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraVolumes: []
extraVolumeMounts: []

extraEnv: {}

service:
  type: NodePort
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
