dependencies:
  - name: redis
    version: 9.1.12
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: postgresql
    version: 6.3.9
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: rabbitmq
    version: 6.7.4
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: reana-server
    version: 0.1.0
    condition: global.reanaServer.enabled
    repository: file://subcharts/reana-server
  - name: reana-workflow-controller
    version: 0.1.0
    repository: file://subcharts/reana-workflow-controller
  - name: reana-ui
    version: 0.1.0
    condition: reanaUi.enabled
    repository: file://subcharts/reana-ui
  - name: reana-wdb
    version: 0.1.0
    condition: reanaWdb.enabled
    repository: file://subcharts/reana-wdb
