global:
  storageClass: manila-csicephfs-share

cern: &cern
  consumerKey: ""
  consumerSecret: ""

gitlab: &gitlab
  host: "gitlab.cern.ch"
  oauthAppId: ""
  oauthAppSecret: ""
  oauthAppSecret: ""
  oauthRedirectUrl: ""

hostName: &hostName reana-dev.cern.ch

sharedVolume: &sharedVolume
  extraVolumeMounts:
    - name: &sharedVolumeName  reana-server-shared-volume
      mountPath: &sharedVolumePath "/var/reana"
  extraVolumes:
    - name: *sharedVolumeName
      persistentVolumeClaim:
        claimName: manila-cephfs-pvc
        readOnly: false
  extraEnv:
    - name: SHARED_VOLUME_PATH
      value: *sharedVolumePath
    - name: REANA_STORAGE_BACKEND
      value: "cephfs"

reanaCephFS:
  enabled: true
  cephAuthUrl: ""
  cephUserId: ""
  cephUserName: ""
  cephPassword: ""
  cephProjectId: ""
  cephDomainId: ""
  cephDomainName: ""
  cephRegion: ""

reana-server:
  hostName: *hostName
  gitlab: *gitlab
  cern: *cern
  <<: *sharedVolume

reana-workflow-controller:
  hostName: *hostName
  gitlab: *gitlab
  <<: *sharedVolume

reana-ui:
  enabled: true

reana-wdb:
  enabled: true

postgresql:
  persistence:
    mountPath: /var/reana/db

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "http,https"
  tls: []
