apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  template:
    spec:
      containers:
        - env:
            - name: TZ
              value: "Europe/Zurich"
          name: postgresql
