apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reana-workflow-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reana-workflow-controller
    spec:
      containers:
        - name: job-status-consumer
          image: reanahub/reana-workflow-controller:0.5.0
          command: ["flask", "consume-job-queue"]
          env:
            - name: REANA_GITLAB_HOST
              value: gitlab.com
        - name: rest-api-server
          image: reanahub/reana-workflow-controller:0.5.0
          env:
            - name: REANA_GITLAB_HOST
              value: gitlab.com
            - name: REANA_DEPLOYMENT_TYPE
              value: local
          ports:
            - name: rest-api
              containerPort: 5000
