apiVersion: v1
kind: Service
metadata:
  name: reana-workflow-controller
spec:
  ports:
    - name: rest-api
      port: 80
      targetPort: rest-api
  selector:
    app: reana-workflow-controller
  type: ClusterIP
