apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "reana-workflow-controller.fullname" . }}
  labels:
{{ include "reana-workflow-controller.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reana-workflow-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: job-status-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["flask", "consume-job-queue"]
          volumeMounts:
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 9 }}
            {{- end }}
          env:
            - name: REANA_GITLAB_HOST
              value: {{ .Values.gitlab.host }}
            - name: REANA_DB_HOST
              value: reana-postgresql
            {{- if .Values.global.postgresql.servicePort }}
            - name: REANA_DB_PORT
              value: {{ .Values.global.postgresql.servicePort }}
            {{- end }}
            - name: REANA_DB_NAME
              value: {{ .Values.global.postgresql.postgresqlDatabase }}
            - name: REANA_DB_USERNAME
              value: {{ .Values.global.postgresql.postgresqlUsername }}
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reana-postgresql
                  key: password
{{- if .Values.extraEnv }}
{{ tpl (toYaml .Values.extraEnv) $ | indent 12 }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: rest-api-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.debug }}
          command: ["/bin/sh","-c"]
          args: ["flask", "run", "--host=0.0.0.0"]
          tty: true
          stdin: true
          {{- end }}
          volumeMounts:
            - name: svaccount
              mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 9 }}
            {{- end }}
          ports:
            - name: rest-api
              containerPort: 5000
          env:
            - name: REANA_GITLAB_HOST
              value: {{ .Values.gitlab.host }}
            - name: REANA_DB_HOST
              value: reana-postgresql
            - name: REANA_DB_PORT
              value: {{ .Values.global.postgresql.servicePort }}
            - name: REANA_DB_USERNAME
              value: {{ .Values.global.postgresql.postgresqlUsername }}
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reana-postgresql
                  key: password
            - name: REANA_DEPLOYMENT_TYPE
              value: {{ .Values.deploymentType }}
            {{- with .Values.hostName }}
            - name: REANA_URL
              value: {{ . }}
            {{- end }}
{{- if .Values.extraEnv }}
{{ tpl (toYaml .Values.extraEnv) $ | indent 12 }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: svaccount
          secret:
            secretName: {{ .Values.apiServerSecret }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 7 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
