apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: reana
deploy:
  kustomize:
    path: manifest/prod/base/kustomization.yaml
profiles:
  - activation:
      - env: ENV=development
        kubeContext: minikube
        command: dev
    deploy:
      kustomize:
        path: manifest/dev/kustomization.yaml
    name: dev
  - activation:
      - env: ENV=production
        kubeContext: cern
        command: prod
    deploy:
      kustomize:
        path: manifest/prod/cern/kustomization.yaml
    name: dev
