apiVersion: v1
kind: Service
metadata:
  name: {{ include "reanaworkflowcontroller.fullname" . }}
  labels:
{{ include "reanaworkflowcontroller.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rest-api
      port: {{ .Values.service.port }}
      targetPort: rest-api
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "reanaworkflowcontroller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
