apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reana-server
spec:
  template:
    spec:
      containers:
        - name: server
          volumeMounts:
            - mountPath: /code
              name: reana-server-code
      volumes:
        - hostPath:
            path: /code/reana-server
          name: reana-server-code
