apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
resources:
  - ingress.yaml
patchesStrategicMerge:
  - reana-server/deploy-patch.yaml
  - reana-workflow-controller/deploy-patch.yaml
  - reana-message-broker/statefulset-patch.yaml
