apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reana-workflow-controller
spec:
  selector:
    matchLabels: &containerLabels
      app: reana-workflow-controller
  template:
    metadata:
      labels: *containerLabels
    spec:
      containers:
        - name: job-status-consumer
          image: reanahub/reana-workflow-controller
          command: ["flask", "consume-job-queue"]
          env:
            - name: REANA_GITLAB_HOST
              value: gitlab.com
          resources:
            limits:
              cpu: 2
              memory: 512M
        - name: rest-api-server
          image: reanahub/reana-workflow-controller
          env:
            - name: REANA_GITLAB_HOST
              value: gitlab.com
            - name: REANA_DEPLOYMENT_TYPE
              value: local
          ports:
            - name: rest-api
              containerPort: 5000
          resources:
            limits:
              cpu: 2
              memory: 512M
