apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "reana.fullname" . }}
  labels:
{{ include "reana.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reana.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.debug }}
          command: ["/bin/sh","-c"]
          args: ["set -e; ./scripts/setup; invenio run -h 0.0.0.0 -p 5000"]
          tty: true
          stdin: true
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.sharedVolumePath  }}
              name: reana-shared-volume
            {{- range .Values.mounts }}
            - name: {{ .name }}
              mountPath: {{ .path | quote }}
            {{- end }}
          ports:
            - name: rest-api
              containerPort: 5000
          env:
            - name: REANA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: user
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: password
            {{- with .Values.url }}
            - name: REANA_URL
              value: {{ . }}
            {{- end }}
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["flask", "start-scheduler"]
          volumeMounts:
            - mountPath: {{ .Values.sharedVolumePath  }}
              name: reana-shared-volume
            {{- range .Values.mounts }}
            - name: {{ .name }}
              mountPath: {{ .path | quote }}
            {{- end }}
          env:
            - name: REANA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: user
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: password
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
      volumes:
        - name: reana-shared-volume
          {{- if .Values.cephFS.enabled }}
          persistentVolumeClaim:
            claimName: manila-cephfs-pvc
            readOnly: false
          {{- else }}
          hostPath:
            path: {{ .Values.rootPath }}
          {{- end }}
        {{- range .Values.mounts }}
        - name: {{ .name }}
          {{ .type }}:
            path: {{ .path | quote }}
        {{- end }}
