apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manila-csicephfs-share
  labels:
{{ include "reana.labels" . | indent 4 }}
provisioner: manila-provisioner
parameters:
  type: "Geneva CephFS Testing"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: csi-cephfsplugin
