apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reana-server
spec:
  template:
    metadata:
      labels:
        app: reana-server
    spec:
      containers:
        - env:
            - name: REANA_URL
              value: reana-dev.cern.ch
          name: server
      volumes:
        - name: reana-shared-volume
          persistentVolumeClaim:
            claimName: manila-cephfs-pvc
            readOnly: false
