replicaCount: 1

image:
  repository: reanahub/reana-ui
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

mounts: []

service:
  type: NodePort
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
