apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reana-server
spec:
  template:
    spec:
      containers:
        - args: ["set -e; ./scripts/setup; invenio run -h 0.0.0.0 -p 5000"]
          command: ["/bin/sh", "-c"]
          name: server
          stdin: true
          tty: true
