dependencies:
  - name: redis
    version: 9.1.12
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: postgresql
    version: 6.3.9
    repository: https://kubernetes-charts.storage.googleapis.com/
