apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
  - ../../base
patchesStrategicMerge:
  - reana-server/deploy-patch.yaml
  - reana-workflow-controller/deploy-patch.yaml
resources:
  - reana-cephfs-storageclass.yaml
  - reana-ingress.yaml
