apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "reana-message-broker.fullname" . }}
  labels:
{{ include "reana-message-broker.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reana-message-broker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            {{- range .Values.mounts }}
            - name: {{ .name }}
              mountPath: {{ .path | quote }}
            {{- end }}
          ports:
            - name: amqp
              containerPort: 5672
            - name: ui
              containerPort: 15672
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- range .Values.mounts }}
        - name: {{ .name }}
          {{ .type }}:
            path: {{ .path | quote }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
