apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  template:
    spec:
      containers:
        - env:
            - name: BITNAMI_DEBUG
              value: "false"
          name: postgresql
