apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: default
data:
  os-authURL: {{ .Values.global.ceph.cephAuthUrl }}
  os-userID: {{ .Values.global.ceph.cephUserId }}
  os-userName: {{ .Values.global.ceph.cephUserName }}
  os-password: {{ .Values.global.ceph.cephPassword }}
  os-projectID: {{ .Values.global.ceph.cephProjectId }}
  os-domainID: {{ .Values.global.ceph.cephDomainId }}
  os-domainName: {{ .Values.global.ceph.cephDomainName }}
  os-region: {{ .Values.global.ceph.cephRegion }}
