apiVersion: v1
kind: Service
metadata:
  name: {{ include "reana-server.fullname" . }}
  labels:
{{ include "reana-server.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - name: rest-api
      port: 80
      targetPort: rest-api
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "reana-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
