apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  selector:
    matchLabels: &containerLabels
      app: postgresql
      role: master
  serviceName: postgresql-headless
  template:
    metadata:
      labels: *containerLabels
      name: postgresql
    spec:
      containers:
        - env:
            - name: TZ
              value: "Europe/Zurich"
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_VOLUME_DIR
              value: /opt/bitnami/postgresql
            - name: PGDATA
              value: /opt/bitnami/postgresql/data
            - name: POSTGRES_USER
              value: reana
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: postgresql
          image: docker.io/bitnami/postgresql
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
            failureThreshold: 6
            initialDelaySeconds: 30
            timeoutSeconds: 5
          name: postgresql
          ports:
            - containerPort: 5432
              name: postgresql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -U "postgres" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ]
            failureThreshold: 6
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsUser: 1001
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: data
      initContainers:
        - command:
            - sh
            - -c
            - |
              mkdir -p /opt/bitnami/postgresql/data
              chmod 700 /opt/bitnami/postgresql/data
              find /bitnami/postgresql -mindepth 0 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
                xargs chown -R 1001:1001
          image: docker.io/bitnami/minideb
          imagePullPolicy: Always
          name: init-chmod-data
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - mountPath: /opt/bitnami/postgresql
              name: data
      securityContext:
        fsGroup: 1001
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
