apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reana-ui
spec:
  selector:
    matchLabels: &containerLabels
      app: reana-ui
  template:
    metadata:
      labels: *containerLabels
    spec:
      containers:
        - image: reanahub/reana-ui
          name: reana-ui
          ports:
            - containerPort: 80
              name: ui
          resources:
            limits:
              cpu: 1
              memory: 512M
