apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "reana-workflow-controller.fullname" . }}
  labels:
{{ include "reana-workflow-controller.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reana-workflow-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: job-status-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["flask", "consume-job-queue"]
          volumeMounts:
            - name: reana-shared-volume
              mountPath: {{ .Values.sharedVolumePath }}
          env:
            - name: REANA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: user
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: password
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: rest-api-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.debug }}
          command: ["/bin/sh","-c"]
          args: ["flask", "run", "--host=0.0.0.0"]
          tty: true
          stdin: true
          {{- end }}
          volumeMounts:
            - name: svaccount
              mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
            - name: reana-shared-volume
              mountPath: {{ .Values.sharedVolumePath }}
            {{- range .Values.mounts }}
            - name: {{ .name }}
              mountPath: {{ .path | quote }}
            {{- end }}
          ports:
            - name: rest-api
              containerPort: 5000
          env:
            - name: REANA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: user
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: password
            - name: REANA_DEPLOYMENT_TYPE
              value: {{ .Values.deploymentType }}
            {{- with .Values.url }}
            - name: REANA_URL
              value: {{ . }}
            {{- end }}
            {{- if .Values.cephFS.enabled }}
            - name: REANA_STORAGE_BACKEND
              value: "cephfs"
            {{- end }}
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
      volumes:
        - name: svaccount
          secret:
            secretName: {{ .Values.apiServerSecret }}
        - name: reana-shared-volume
          {{- if .Values.cephFS.enabled }}
          persistentVolumeClaim:
            claimName: manila-cephfs-pvc
            readOnly: false
          {{- else }}
          hostPath:
            path: {{ .Values.rootPath }}
          {{- end }}
        {{- range .Values.mounts }}
        - name: {{ .name }}
          {{ .type }}:
            path: {{ .path }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
