apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "reana.fullname" . }}
  labels:
{{ include "reana.labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reana.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.debug }}
          command: ["/bin/sh","-c"]
          args: ["set -e; ./scripts/setup; invenio run -h 0.0.0.0 -p 5000"]
          tty: true
          stdin: true
          {{- end }}
          volumeMounts:
            - mountPath: {{SHARED_VOLUME_PATH}}
              name: reana-shared-volume
            {% set mountpoints=RS_MOUNTPOINTS %}
            {% for mount in mountpoints %}
            - mountPath: {{mount['path'].split(':')[1]}}
              name: {{mount['name']}}
            {% endfor %}
          ports:
            - name: http
              containerPort: 5000
          env:
            {{- if .Values.url }}
            - name: REANA_URL
              value: {{ .Values.url }}
            {{- end }}
            {% set environment=RS_ENVIRONMENT %}
            {% for envvar in environment %}
            {% for key, value in envvar.items() %}
            - name: {{key}}
              value: "{{value}}"
            {% endfor %}
            {% endfor %}
            {% if not DEBUG %}
            - name: REANA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: user
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reana-db-secrets
                  key: password
            {% endif %}
        - name: scheduler
          image: {{SERVER_IMAGE}}
          command: ["flask", "start-scheduler"]
          imagePullPolicy: {{IMAGE_PULL_POLICY}}
          volumeMounts:
          - mountPath: {{SHARED_VOLUME_PATH}}
            name: reana-shared-volume
          {% set mountpoints=RS_MOUNTPOINTS %}
          {% for mount in mountpoints %}
          - mountPath: {{mount['path'].split(':')[1]}}
            name: {{mount['name']}}
          {% endfor %}
          env:
          {% set environment=RS_ENVIRONMENT %}
          {% for envvar in environment %}
          {% for key, value in envvar.items() %}
          - name: {{key}}
            value: "{{value}}"
          {% endfor %}
          {% endfor %}
          {% if not DEBUG %}
          - name: REANA_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: reana-db-secrets
                key: user
          - name: REANA_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: reana-db-secrets
                key: password
          {% endif %}
        volumes:
        - name: reana-shared-volume
          {% if CEPHFS %}
          persistentVolumeClaim:
            claimName: manila-cephfs-pvc
            readOnly: false
          {% else %}
          hostPath:
            path: {{ROOT_PATH}}
          {% endif %}
        {% for mount in mountpoints %}
        - name: {{mount['name']}}
          {{mount['type']}}:
            path: {{mount['path'].split(':')[0]}}
        {% endfor %}
